/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'
import { Route as TagsSlugRouteImport } from './routes/tags.$slug'
import { Route as AdminRecipesNewRouteImport } from './routes/admin.recipes.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AdminRecipesIdEditRouteImport } from './routes/admin.recipes.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSlugRoute = TagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecipesNewRoute = AdminRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecipesIdEditRoute = AdminRecipesIdEditRouteImport.update({
  id: '/recipes/$id/edit',
  path: '/recipes/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/recipes/$id/edit': typeof AdminRecipesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/recipes/$id/edit': typeof AdminRecipesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/recipes/$id/edit': typeof AdminRecipesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/health'
    | '/recipes/$slug'
    | '/tags/$slug'
    | '/admin/'
    | '/recipes/'
    | '/admin/recipes/new'
    | '/api/auth/$'
    | '/admin/recipes/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/recipes/$slug'
    | '/tags/$slug'
    | '/admin'
    | '/recipes'
    | '/admin/recipes/new'
    | '/api/auth/$'
    | '/admin/recipes/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/health'
    | '/recipes/$slug'
    | '/tags/$slug'
    | '/admin/'
    | '/recipes/'
    | '/admin/recipes/new'
    | '/api/auth/$'
    | '/admin/recipes/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  TagsSlugRoute: typeof TagsSlugRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$slug': {
      id: '/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof TagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recipes/new': {
      id: '/admin/recipes/new'
      path: '/recipes/new'
      fullPath: '/admin/recipes/new'
      preLoaderRoute: typeof AdminRecipesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recipes/$id/edit': {
      id: '/admin/recipes/$id/edit'
      path: '/recipes/$id/edit'
      fullPath: '/admin/recipes/$id/edit'
      preLoaderRoute: typeof AdminRecipesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRecipesNewRoute: typeof AdminRecipesNewRoute
  AdminRecipesIdEditRoute: typeof AdminRecipesIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminRecipesNewRoute: AdminRecipesNewRoute,
  AdminRecipesIdEditRoute: AdminRecipesIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  TagsSlugRoute: TagsSlugRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
