/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'
import { Route as TagsSlugRouteImport } from './routes/tags.$slug'
import { Route as AdminCollectionsIndexRouteImport } from './routes/admin.collections.index'
import { Route as AdminCollectionsNewRouteImport } from './routes/admin.collections.new'
import { Route as AdminRecipesNewRouteImport } from './routes/admin.recipes.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AdminCollectionsIdEditRouteImport } from './routes/admin.collections.$id.edit'
import { Route as AdminRecipesIdEditRouteImport } from './routes/admin.recipes.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSlugRoute = TagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionsIndexRoute = AdminCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsNewRoute = AdminCollectionsNewRouteImport.update({
  id: '/collections/new',
  path: '/collections/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesNewRoute = AdminRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionsIdEditRoute = AdminCollectionsIdEditRouteImport.update({
  id: '/collections/$id/edit',
  path: '/collections/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesIdEditRoute = AdminRecipesIdEditRouteImport.update({
  id: '/recipes/$id/edit',
  path: '/recipes/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/collections/$id/edit': typeof AdminCollectionsIdEditRoute
  '/admin/recipes/$id/edit': typeof AdminRecipesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/collections': typeof AdminCollectionsIndexRoute
  '/admin/collections/$id/edit': typeof AdminCollectionsIdEditRoute
  '/admin/recipes/$id/edit': typeof AdminRecipesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/collections/$id/edit': typeof AdminCollectionsIdEditRoute
  '/admin/recipes/$id/edit': typeof AdminRecipesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/api/health'
    | '/collections/$slug'
    | '/recipes/$slug'
    | '/tags/$slug'
    | '/admin/'
    | '/recipes/'
    | '/admin/collections/new'
    | '/admin/recipes/new'
    | '/api/auth/$'
    | '/admin/collections/'
    | '/admin/collections/$id/edit'
    | '/admin/recipes/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/api/health'
    | '/collections/$slug'
    | '/recipes/$slug'
    | '/tags/$slug'
    | '/admin'
    | '/recipes'
    | '/admin/collections/new'
    | '/admin/recipes/new'
    | '/api/auth/$'
    | '/admin/collections'
    | '/admin/collections/$id/edit'
    | '/admin/recipes/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/api/health'
    | '/collections/$slug'
    | '/recipes/$slug'
    | '/tags/$slug'
    | '/admin/'
    | '/recipes/'
    | '/admin/collections/new'
    | '/admin/recipes/new'
    | '/api/auth/$'
    | '/admin/collections/'
    | '/admin/collections/$id/edit'
    | '/admin/recipes/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  TagsSlugRoute: typeof TagsSlugRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$slug': {
      id: '/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof TagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections/': {
      id: '/admin/collections/'
      path: '/collections'
      fullPath: '/admin/collections/'
      preLoaderRoute: typeof AdminCollectionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/new': {
      id: '/admin/collections/new'
      path: '/collections/new'
      fullPath: '/admin/collections/new'
      preLoaderRoute: typeof AdminCollectionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes/new': {
      id: '/admin/recipes/new'
      path: '/recipes/new'
      fullPath: '/admin/recipes/new'
      preLoaderRoute: typeof AdminRecipesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections/$id/edit': {
      id: '/admin/collections/$id/edit'
      path: '/collections/$id/edit'
      fullPath: '/admin/collections/$id/edit'
      preLoaderRoute: typeof AdminCollectionsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes/$id/edit': {
      id: '/admin/recipes/$id/edit'
      path: '/recipes/$id/edit'
      fullPath: '/admin/recipes/$id/edit'
      preLoaderRoute: typeof AdminRecipesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCollectionsNewRoute: typeof AdminCollectionsNewRoute
  AdminRecipesNewRoute: typeof AdminRecipesNewRoute
  AdminCollectionsIndexRoute: typeof AdminCollectionsIndexRoute
  AdminCollectionsIdEditRoute: typeof AdminCollectionsIdEditRoute
  AdminRecipesIdEditRoute: typeof AdminRecipesIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCollectionsNewRoute: AdminCollectionsNewRoute,
  AdminRecipesNewRoute: AdminRecipesNewRoute,
  AdminCollectionsIndexRoute: AdminCollectionsIndexRoute,
  AdminCollectionsIdEditRoute: AdminCollectionsIdEditRoute,
  AdminRecipesIdEditRoute: AdminRecipesIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  TagsSlugRoute: TagsSlugRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
